name: Raise version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New release version'
        required: true
        type: string
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: '24.11.1'
          registry-url: 'https://registry.npmjs.org'
          scope: '@stefanhasenberg'
      - run: yarn
      - run: git config --global user.email "stefan.hasenberg@vodafonemail.de"
      - run: git config --global user.name "Stefan Hasenberg"
      - run: yarn version --new-version $VERSION
        env:
          VERSION: ${{inputs.version}}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_PUSH_TOKEN }}
          branch: release

